### ISSUE TITLE
Replace backendutil.TransformBackend

### ISSUE THREAD

**Issue by foxcpp** [mback2k/smtp-dkim-signer#1]
TransformBackend was recently [removed][1] from the master branch of go-smtp. You may want to update your signer proxy to not use it.

[1]: https://github.com/emersion/go-smtp/pull/31

**Comment by mback2k** [comment]
@foxcpp That is very sad, because my little program is basically built around the TransformBackend. I will have to take a look how to re-write it then.

**Comment by mback2k** [comment]
For now I have delayed the need to adapt, by enabling Go modules with 3c8b54f9d4730d783057a665a3f9522a670628df and pinning an older version of go-smtp and go-dkim.

**Comment by mback2k** [comment]
Working on this via https://github.com/emersion/go-smtp/pull/47.

**Comment by mback2k** [comment]
Relevant commit is 87b143dbc58064d456c8eedea843f180f1b85d7e.

**Comment by mback2k** [comment]
Finally completely removed the use of TransformBackend. This issue can now be closed.
