### ISSUE TITLE
Migrate to go-msgauth

### ISSUE THREAD

**Issue by emersion** [mback2k/smtp-dkim-signer#2]
go-dkim has been migrated to [go-msgauth](https://github.com/emersion/go-msgauth) and won't receive updates anymore

**Comment by mback2k** [comment]
Thanks, already on it together with the updates to go-smtp-proxy and reintroduction of the TransformBackend in the testing branch.

**Comment by mback2k** [comment]
Relevant commit is 674e0720641237d6166dc903e37aedc180e1a495.

**Comment by mback2k** [comment]
Migrated to go-msgauth in master branch. This issue can now be closed.
